# Generated by Django 4.0.5 on 2023-01-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authorList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(max_length=250, verbose_name='Author ID')),
                ('author_firstName', models.CharField(max_length=500, verbose_name='First Name')),
                ('author_lastName', models.CharField(max_length=500, verbose_name='Last Name')),
            ],
        ),
        migrations.CreateModel(
            name='bookAuthorList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=250, verbose_name='Book Id')),
                ('author_id', models.CharField(max_length=250, verbose_name='Author ID')),
            ],
        ),
        migrations.CreateModel(
            name='booklendList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lend_id', models.CharField(max_length=250, verbose_name='ID')),
                ('book_id', models.CharField(max_length=250, verbose_name='Book Id')),
                ('member_id', models.CharField(max_length=250, verbose_name='Member ID')),
                ('lend_date', models.DateField(max_length=250, verbose_name='Lend On')),
                ('returned_date', models.DateField(max_length=250, verbose_name='Returned On')),
                ('return_status', models.CharField(max_length=250, verbose_name='Return Status')),
            ],
        ),
        migrations.CreateModel(
            name='booksList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=250, verbose_name='Id')),
                ('book_title', models.CharField(max_length=500, verbose_name='Name')),
                ('cat_id', models.CharField(max_length=250, verbose_name='Category ID')),
                ('pub_date', models.CharField(max_length=250, verbose_name='Publication Date')),
                ('copies_own', models.IntegerField(verbose_name='Copies')),
            ],
        ),
        migrations.CreateModel(
            name='categoryListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.CharField(max_length=250, verbose_name='Category ID')),
                ('cat_name', models.CharField(max_length=500, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='fineList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_id', models.CharField(max_length=250, verbose_name='ID')),
                ('late_id', models.CharField(max_length=250, verbose_name='Late ID')),
                ('fine_amount', models.IntegerField(verbose_name='Amount')),
                ('fine_status', models.CharField(max_length=250, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='lateList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('late_id', models.CharField(max_length=250, verbose_name='Late ID')),
                ('member_id', models.CharField(max_length=250, verbose_name='Member ID')),
                ('book_id', models.CharField(max_length=250, verbose_name='Book Id')),
                ('lend_id', models.CharField(max_length=250, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='memberList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=250, verbose_name='ID')),
                ('member_firstName', models.CharField(max_length=500, verbose_name='First Name')),
                ('member_lastName', models.CharField(max_length=500, verbose_name='Last Name')),
                ('date_joined', models.DateField(max_length=250, verbose_name='Date Joined')),
                ('status_id', models.DateField(max_length=250, verbose_name='Status ID')),
            ],
        ),
        migrations.CreateModel(
            name='memberStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.DateField(max_length=250, verbose_name='Status ID')),
                ('status_value', models.CharField(max_length=250, verbose_name='Status Value')),
            ],
        ),
        migrations.CreateModel(
            name='reservationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_id', models.CharField(max_length=250, verbose_name='ID')),
                ('book_id', models.CharField(max_length=250, verbose_name='Book Id')),
                ('member_id', models.CharField(max_length=250, verbose_name='Member ID')),
                ('res_from_date', models.DateField(max_length=250, verbose_name='Reserve From')),
                ('res_to_date', models.DateField(max_length=250, verbose_name='Reserve To')),
                ('res_status_id', models.CharField(max_length=250, verbose_name='Reservation Status')),
            ],
        ),
        migrations.CreateModel(
            name='reservationStatusList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_status_id', models.CharField(max_length=250, verbose_name='Status ID')),
                ('res_status_name', models.CharField(max_length=500, verbose_name='Status')),
            ],
        ),
    ]
