# Generated by Django 4.0.5 on 2023-01-13 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='authorList',
            new_name='authorListModel',
        ),
        migrations.RenameModel(
            old_name='bookAuthorList',
            new_name='bookAuthorListModel',
        ),
        migrations.RenameModel(
            old_name='booklendList',
            new_name='booklendListModel',
        ),
        migrations.RenameModel(
            old_name='booksList',
            new_name='booksListModel',
        ),
        migrations.RenameModel(
            old_name='fineList',
            new_name='fineListModel',
        ),
        migrations.RenameModel(
            old_name='lateList',
            new_name='lateListModel',
        ),
        migrations.RenameModel(
            old_name='memberList',
            new_name='memberListModel',
        ),
        migrations.RenameModel(
            old_name='memberStatus',
            new_name='memberStatusModel',
        ),
        migrations.RenameModel(
            old_name='reservationList',
            new_name='reservationListModel',
        ),
        migrations.RenameModel(
            old_name='reservationStatusList',
            new_name='reservationStatusListModel',
        ),
    ]
